version: '3'
services:
  web:
    build: 
        context: .
        dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ~/Projects/Docker/frontend:/home/node/app
      - /home/node/app/node_modules
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ~/Projects/Docker/frontend:/home/node/app
      - /home/node/app/node_modules
    command: ["npm", "run", "test"]